# Opciones de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Opciones de Springdoc OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha