# Opciones de Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Configuración de CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Deshabilitar Springdoc OpenAPI en producción
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false