spring.application.name=poc-springboot
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# Parámetros de conexión a base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Opciones de Hibernate
spring.jpa.open-in-view=false

# Opciones de Spring Security
security.user.name=${SECURITY_USER_NAME}
security.user.password=${SECURITY_USER_PASSWORD}

# Opciones de OAuth2 Resource Server
spring.security.oauth2.client.registration.keycloak.client-id=${KEYCLOAK_CLIENT_ID}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.redirect-uri=${KEYCLOAK_REDIRECT_URI}

spring.security.oauth2.client.provider.keycloak.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

# Opciones de logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.file.name=/var/logs/poc-springboot.log