spring.application.name=poc-springboot
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Database connection details
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sabordb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Spring Security settings
security.user.name=${SECURITY_USER_NAME:admin}
security.user.password=${SECURITY_USER_PASSWORD:admin}