spring.application.name=poc-springboot
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Parámetros de conexión a base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sabordb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

# Opciones de Hibernate
spring.jpa.open-in-view=false

# Opciones de Spring Security
security.user.name=${SECURITY_USER_NAME:admin}
security.user.password=${SECURITY_USER_PASSWORD:admin}